/**
 * API request/response types — shared between the Fastify API and dashboard.
 */

import { z } from "zod";
import {
  StorageTierSchema,
  CriticalitySchema,
  SeveritySchema,
  PolicyDocumentSchema,
} from "./policy.js";

// ─────────────────────────────────────────────────────────────────────
// Contract Registration
// ─────────────────────────────────────────────────────────────────────

/** Register a new Soroban contract for monitoring. */
export const ContractRegistrationSchema = z.object({
  /** Soroban contract ID (C...). */
  contract_id: z
    .string()
    .regex(/^C[A-Z0-9]{55}$/, "Invalid Soroban contract ID format"),
  /** Human-readable name for this contract. */
  name: z.string().min(1).max(128),
  /** Network: testnet, mainnet, futurenet. */
  network: z.enum(["testnet", "mainnet", "futurenet"]),
  /** Optional parsed policy document. */
  policy: PolicyDocumentSchema.optional(),
  /** Optional raw policy TOML string (parsed server-side). */
  policy_toml: z.string().optional(),
  /** Tags for categorization. */
  tags: z.array(z.string()).default([]),
});
export type ContractRegistration = z.infer<typeof ContractRegistrationSchema>;

// ─────────────────────────────────────────────────────────────────────
// TTL Snapshots (Time-series readings)
// ─────────────────────────────────────────────────────────────────────

/** A point-in-time TTL reading for a specific state key. */
export const TtlSnapshotSchema = z.object({
  id: z.string().uuid().optional(),
  contract_id: z.string(),
  /** State key identifier (e.g., "UserPosition", "Config"). */
  key_name: z.string(),
  /** Storage tier. */
  tier: StorageTierSchema,
  /** Current TTL in ledgers remaining. */
  ttl_ledgers: z.number().int().nonnegative(),
  /** Ledger sequence at time of reading. */
  ledger_sequence: z.number().int().positive(),
  /** Estimated expiry timestamp (computed from ledger close time). */
  estimated_expiry: z.string().datetime().optional(),
  /** Health score: 0.0 (expired/archived) → 1.0 (fully healthy). */
  health_score: z.number().min(0).max(1),
  /** Criticality of this state entry. */
  criticality: CriticalitySchema,
  /** ISO timestamp of snapshot. */
  recorded_at: z.string().datetime(),
});
export type TtlSnapshot = z.infer<typeof TtlSnapshotSchema>;

// ─────────────────────────────────────────────────────────────────────
// Alerts
// ─────────────────────────────────────────────────────────────────────

/** An alert event generated by the keeper or API. */
export const AlertEventSchema = z.object({
  id: z.string().uuid().optional(),
  contract_id: z.string(),
  key_name: z.string(),
  severity: SeveritySchema,
  /** Alert type. */
  alert_type: z.enum([
    "ttl_below_threshold",
    "ttl_critical",
    "state_archived",
    "renewal_failed",
    "renewal_success",
    "cost_spike",
  ]),
  /** Human-readable message. */
  message: z.string(),
  /** TTL value at time of alert (ledgers). */
  ttl_at_alert: z.number().int().nonnegative().optional(),
  /** Threshold that was breached. */
  threshold: z.number().int().nonnegative().optional(),
  /** Alert channel used (webhook, slack, pagerduty). */
  channel: z.string().optional(),
  /** Whether the alert has been acknowledged. */
  acknowledged: z.boolean().default(false),
  /** Who acknowledged it. */
  acknowledged_by: z.string().optional(),
  /** ISO timestamp. */
  created_at: z.string().datetime(),
});
export type AlertEvent = z.infer<typeof AlertEventSchema>;

// ─────────────────────────────────────────────────────────────────────
// Keeper Jobs
// ─────────────────────────────────────────────────────────────────────

/** A keeper renewal job in the PostgreSQL queue. */
export const KeeperJobSchema = z.object({
  id: z.string().uuid().optional(),
  contract_id: z.string(),
  key_name: z.string(),
  /** Job action type. */
  action: z.enum(["extend_ttl", "restore_footprint"]),
  /** Job status. */
  status: z.enum([
    "pending",
    "claimed",
    "submitted",
    "confirmed",
    "failed",
    "retrying",
  ]),
  /** Transaction hash if submitted. */
  tx_hash: z.string().optional(),
  /** Cost in stroops. */
  cost_stroops: z.number().int().nonnegative().optional(),
  /** Cost in XLM. */
  cost_xlm: z.number().nonnegative().optional(),
  /** Error message on failure. */
  error: z.string().optional(),
  /** Retry count. */
  retry_count: z.number().int().nonnegative().default(0),
  /** Max retries allowed. */
  max_retries: z.number().int().nonnegative().default(3),
  /** Scheduled execution time. */
  scheduled_at: z.string().datetime(),
  /** Actual execution time. */
  executed_at: z.string().datetime().optional(),
  created_at: z.string().datetime(),
});
export type KeeperJob = z.infer<typeof KeeperJobSchema>;

// ─────────────────────────────────────────────────────────────────────
// Dashboard Aggregations
// ─────────────────────────────────────────────────────────────────────

/** Aggregated dashboard summary. */
export const DashboardSummarySchema = z.object({
  total_contracts: z.number().int().nonnegative(),
  total_state_keys: z.number().int().nonnegative(),
  /** Keys by health status bucket. */
  health_distribution: z.object({
    healthy: z.number().int().nonnegative(),
    warning: z.number().int().nonnegative(),
    critical: z.number().int().nonnegative(),
    archived: z.number().int().nonnegative(),
  }),
  /** Active (unacknowledged) alerts. */
  active_alerts: z.number().int().nonnegative(),
  /** Pending keeper jobs. */
  pending_jobs: z.number().int().nonnegative(),
  /** Total XLM spent on renewals (lifetime). */
  total_renewal_cost_xlm: z.number().nonnegative(),
  /** Last snapshot timestamp. */
  last_snapshot_at: z.string().datetime().optional(),
});
export type DashboardSummary = z.infer<typeof DashboardSummarySchema>;

// ─────────────────────────────────────────────────────────────────────
// Cost Estimation
// ─────────────────────────────────────────────────────────────────────

/** Input for a single storage cost estimation line. */
export const CostEstimateEntrySchema = z.object({
  tier: StorageTierSchema,
  /** Number of entries of this type. */
  cardinality: z.number().int().positive(),
  /** Average value size in bytes. */
  value_size_bytes: z.number().int().positive(),
  /** Key size in bytes. */
  key_size_bytes: z.number().int().positive().default(64),
  /** Target TTL in ledgers. */
  target_ttl_ledgers: z.number().int().positive(),
});
export type CostEstimateEntry = z.infer<typeof CostEstimateEntrySchema>;

/** Cost estimation result. */
export const CostEstimateResultSchema = z.object({
  entries: z.array(
    z.object({
      tier: StorageTierSchema,
      cardinality: z.number(),
      size_bytes: z.number(),
      cost_xlm: z.number(),
      cost_per_year_xlm: z.number(),
    })
  ),
  total_xlm: z.number(),
  total_per_year_xlm: z.number(),
  /** Ledger close time assumption (seconds). */
  ledger_close_time_seconds: z.number().default(5),
});
export type CostEstimateResult = z.infer<typeof CostEstimateResultSchema>;

// ─────────────────────────────────────────────────────────────────────
// Health Check
// ─────────────────────────────────────────────────────────────────────

/** Service health status. */
export const HealthStatusSchema = z.object({
  status: z.enum(["healthy", "degraded", "unhealthy"]),
  version: z.string(),
  uptime_seconds: z.number(),
  checks: z.object({
    database: z.enum(["connected", "disconnected"]),
    rpc: z.enum(["reachable", "unreachable"]).optional(),
  }),
});
export type HealthStatus = z.infer<typeof HealthStatusSchema>;

// ─────────────────────────────────────────────────────────────────────
// Pagination
// ─────────────────────────────────────────────────────────────────────

/** Standard pagination parameters. */
export const PaginationSchema = z.object({
  page: z.number().int().positive().default(1),
  per_page: z.number().int().positive().max(100).default(25),
  total: z.number().int().nonnegative().optional(),
  total_pages: z.number().int().nonnegative().optional(),
});
export type Pagination = z.infer<typeof PaginationSchema>;
