"use client";

import { useState } from "react";
import { StorageTier } from "../../lib/types";
import { calculateStorageCost } from "../../lib/api";

export default function CostEstimatorPage() {
  const [tier, setTier] = useState<StorageTier>("persistent");
  const [cardinality, setCardinality] = useState<number>(10000);
  const [keySizeBytes, setKeySizeBytes] = useState<number>(32);
  const [valueSizeBytes, setValueSizeBytes] = useState<number>(256);
  const [targetTtlDays, setTargetTtlDays] = useState<number>(31);
  const [network, setNetwork] = useState<"mainnet" | "testnet">("testnet");
  const [copiedToml, setCopiedToml] = useState(false);

  // 1 day = 17,280 ledgers
  const targetTtlLedgers = targetTtlDays * 17280;

  const result = calculateStorageCost({
    tier,
    cardinality,
    keySizeBytes,
    valueSizeBytes,
    targetTtlLedgers,
    network,
  });

  // Calculate comparisons for all 3 tiers
  const persistentCompare = calculateStorageCost({
    tier: "persistent",
    cardinality,
    keySizeBytes,
    valueSizeBytes,
    targetTtlLedgers,
    network,
  });

  const temporaryCompare = calculateStorageCost({
    tier: "temporary",
    cardinality,
    keySizeBytes,
    valueSizeBytes,
    targetTtlLedgers,
    network,
  });

  const instanceCompare = calculateStorageCost({
    tier: "instance",
    cardinality: Math.min(cardinality, 50), // instance has low cardinality
    keySizeBytes,
    valueSizeBytes,
    targetTtlLedgers,
    network,
  });

  const tomlSnippet = `# Generated by Soroban State Ops Cost Modeler
[policy]
contract_name = "MySorobanContract"
version = "0.1.0"
default_network = "${network}"

[[state_keys]]
name = "EntryData"
tier = "${tier}"
criticality = "${tier === "persistent" ? "critical" : "low"}"
cardinality_hint = "${cardinality > 1000 ? "unbounded" : "bounded"}"

[state_keys.ttl]
mode = "${tier === "persistent" ? "keeper" : "bump-on-access"}"
threshold_ledgers = ${Math.round(targetTtlLedgers * 0.2)}
target_ledgers = ${targetTtlLedgers}
`;

  const copyToml = () => {
    navigator.clipboard.writeText(tomlSnippet);
    setCopiedToml(true);
    setTimeout(() => setCopiedToml(false), 2000);
  };

  return (
    <div className="animate-in">
      {/* Header */}
      <div className="page-header">
        <div>
          <h1 className="page-title">Soroban Storage Rent & Lifecycle Modeler</h1>
          <p className="page-subtitle">
            Simulate on-chain footprint costs, ledger rent decay, and automated keeper renewal overhead under Stellar Protocol 20/21.
          </p>
        </div>
      </div>

      <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "var(--space-2xl)", marginBottom: "var(--space-2xl)" }}>
        {/* Controls Card */}
        <div className="card">
          <h2 style={{ fontSize: "1.2rem", fontWeight: 700, marginBottom: "var(--space-lg)" }}>
            1. Configure Storage Parameters
          </h2>

          <div style={{ display: "flex", flexDirection: "column", gap: "var(--space-lg)" }}>
            {/* Storage Tier selector */}
            <div>
              <label style={{ display: "block", fontSize: "0.85rem", fontWeight: 600, marginBottom: "var(--space-xs)" }}>
                Storage Tier
              </label>
              <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr 1fr", gap: "var(--space-sm)" }}>
                {(["persistent", "temporary", "instance"] as StorageTier[]).map((t) => (
                  <button
                    key={t}
                    type="button"
                    onClick={() => setTier(t)}
                    style={{
                      padding: "var(--space-md) var(--space-sm)",
                      borderRadius: "var(--radius-sm)",
                      border: tier === t ? "2px solid var(--accent-primary)" : "1px solid var(--border-default)",
                      background: tier === t ? "hsla(240, 80%, 65%, 0.15)" : "var(--bg-elevated)",
                      color: tier === t ? "var(--text-primary)" : "var(--text-secondary)",
                      cursor: "pointer",
                      textTransform: "capitalize",
                      fontWeight: 600,
                      fontSize: "0.85rem",
                    }}
                  >
                    {t}
                  </button>
                ))}
              </div>
              <p style={{ fontSize: "0.75rem", color: "var(--text-muted)", marginTop: "var(--space-xs)" }}>
                {tier === "persistent" && "Long-lived data; recoverable via restore_footprint if expired."}
                {tier === "temporary" && "Cheapest rent; deleted permanently on expiry (unrecoverable)."}
                {tier === "instance" && "Tied to contract instance lifetime; loaded on every invocation."}
              </p>
            </div>

            {/* Entry Cardinality */}
            <div>
              <div style={{ display: "flex", justifyContent: "space-between", marginBottom: "var(--space-xs)" }}>
                <label style={{ fontSize: "0.85rem", fontWeight: 600 }}>Entry Count (Cardinality)</label>
                <span className="mono" style={{ fontWeight: 700, color: "var(--accent-primary)" }}>
                  {cardinality.toLocaleString()} entries
                </span>
              </div>
              <input
                type="range"
                min={1}
                max={100000}
                step={100}
                value={cardinality}
                onChange={(e) => setCardinality(Number(e.target.value))}
                style={{ width: "100%", accentColor: "var(--accent-primary)" }}
              />
              <div style={{ display: "flex", gap: "var(--space-sm)", marginTop: "var(--space-xs)" }}>
                {[100, 1000, 10000, 50000].map((n) => (
                  <button
                    key={n}
                    type="button"
                    onClick={() => setCardinality(n)}
                    className="btn btn-ghost"
                    style={{ padding: "2px 8px", fontSize: "0.7rem" }}
                  >
                    {n.toLocaleString()}
                  </button>
                ))}
              </div>
            </div>

            {/* Sizes */}
            <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "var(--space-md)" }}>
              <div>
                <label style={{ display: "block", fontSize: "0.8rem", color: "var(--text-secondary)", marginBottom: 4 }}>
                  Key Size (bytes)
                </label>
                <input
                  type="number"
                  value={keySizeBytes}
                  onChange={(e) => setKeySizeBytes(Number(e.target.value))}
                  style={{
                    width: "100%",
                    padding: "var(--space-sm)",
                    background: "var(--bg-elevated)",
                    border: "1px solid var(--border-default)",
                    borderRadius: "var(--radius-sm)",
                    color: "var(--text-primary)",
                  }}
                />
              </div>
              <div>
                <label style={{ display: "block", fontSize: "0.8rem", color: "var(--text-secondary)", marginBottom: 4 }}>
                  Value Size (bytes)
                </label>
                <input
                  type="number"
                  value={valueSizeBytes}
                  onChange={(e) => setValueSizeBytes(Number(e.target.value))}
                  style={{
                    width: "100%",
                    padding: "var(--space-sm)",
                    background: "var(--bg-elevated)",
                    border: "1px solid var(--border-default)",
                    borderRadius: "var(--radius-sm)",
                    color: "var(--text-primary)",
                  }}
                />
              </div>
            </div>

            {/* Target TTL */}
            <div>
              <div style={{ display: "flex", justifyContent: "space-between", marginBottom: "var(--space-xs)" }}>
                <label style={{ fontSize: "0.85rem", fontWeight: 600 }}>Target TTL Horizon</label>
                <span className="mono" style={{ fontWeight: 700, color: "var(--accent-primary)" }}>
                  {targetTtlDays} days ({targetTtlLedgers.toLocaleString()} ledgers)
                </span>
              </div>
              <input
                type="range"
                min={1}
                max={365}
                value={targetTtlDays}
                onChange={(e) => setTargetTtlDays(Number(e.target.value))}
                style={{ width: "100%", accentColor: "var(--accent-primary)" }}
              />
            </div>
          </div>
        </div>

        {/* Results Card */}
        <div className="card" style={{ display: "flex", flexDirection: "column", justifyContent: "space-between" }}>
          <div>
            <h2 style={{ fontSize: "1.2rem", fontWeight: 700, marginBottom: "var(--space-lg)" }}>
              2. Projected State Rent & Operational Costs
            </h2>

            <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "var(--space-md)", marginBottom: "var(--space-xl)" }}>
              <div style={{ background: "var(--bg-elevated)", padding: "var(--space-md)", borderRadius: "var(--radius-md)" }}>
                <div className="stat-label">Initial Footprint Write</div>
                <div style={{ fontSize: "1.5rem", fontWeight: 800, color: "var(--text-primary)" }}>
                  {result.initialWriteXlm.toFixed(3)} XLM
                </div>
                <div style={{ fontSize: "0.75rem", color: "var(--text-muted)" }}>
                  {result.totalStorageBytes.toLocaleString()} bytes total
                </div>
              </div>

              <div style={{ background: "var(--bg-elevated)", padding: "var(--space-md)", borderRadius: "var(--radius-md)" }}>
                <div className="stat-label">Monthly Rent Burn</div>
                <div style={{ fontSize: "1.5rem", fontWeight: 800, color: "var(--color-warning)" }}>
                  {result.rentPerMonthXlm.toFixed(4)} XLM
                </div>
                <div style={{ fontSize: "0.75rem", color: "var(--text-muted)" }}>
                  ~{(result.rentPerDayXlm).toFixed(5)} XLM / day
                </div>
              </div>
            </div>

            <div
              style={{
                background: "linear-gradient(135deg, hsla(240, 80%, 65%, 0.15), hsla(280, 70%, 55%, 0.1))",
                padding: "var(--space-lg)",
                borderRadius: "var(--radius-md)",
                border: "1px solid hsla(240, 80%, 65%, 0.3)",
                marginBottom: "var(--space-xl)",
              }}
            >
              <div className="stat-label">Total Annual Cost (Rent + Keeper Gas)</div>
              <div style={{ fontSize: "2.2rem", fontWeight: 800, color: "var(--text-primary)" }}>
                {result.totalAnnualCostXlm.toFixed(3)} XLM
              </div>
              <div style={{ fontSize: "0.85rem", color: "var(--text-secondary)", marginTop: "var(--space-xs)" }}>
                Includes {result.renewalCyclesPerYear} automated keeper renewals/year ({result.annualRenewalFeeXlm.toFixed(3)} XLM gas)
              </div>
            </div>

            {/* Tier Comparison Summary */}
            <div style={{ fontSize: "0.85rem", marginBottom: "var(--space-md)" }}>
              <div style={{ fontWeight: 600, marginBottom: "var(--space-xs)" }}>Annual Cost Comparison:</div>
              <div style={{ display: "flex", justifyContent: "space-between", padding: "4px 0", color: "var(--text-secondary)" }}>
                <span>Persistent Tier:</span>
                <span className="mono" style={{ fontWeight: 600 }}>{persistentCompare.totalAnnualCostXlm.toFixed(3)} XLM/yr</span>
              </div>
              <div style={{ display: "flex", justifyContent: "space-between", padding: "4px 0", color: "var(--color-healthy)" }}>
                <span>Temporary Tier (Savings):</span>
                <span className="mono" style={{ fontWeight: 600 }}>{temporaryCompare.totalAnnualCostXlm.toFixed(3)} XLM/yr (saves ~75%)</span>
              </div>
            </div>
          </div>

          {/* Advice */}
          <div
            style={{
              padding: "var(--space-md)",
              borderRadius: "var(--radius-sm)",
              background: "hsla(200, 80%, 60%, 0.1)",
              border: "1px solid hsla(200, 80%, 60%, 0.25)",
              fontSize: "0.8rem",
              color: "var(--color-info)",
            }}
          >
            💡 <strong>State Policy Tip:</strong> For high-cardinality collections, ensure your smart contract invokes <code>extend_ttl</code> only when entries approach threshold to minimize invocation fee overhead.
          </div>
        </div>
      </div>

      {/* Export Policy TOML */}
      <div className="card">
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "var(--space-md)" }}>
          <div>
            <h2 style={{ fontSize: "1.1rem", fontWeight: 700 }}>Export as State Policy Configuration (TOML)</h2>
            <p style={{ fontSize: "0.8rem", color: "var(--text-muted)" }}>
              Directly importable into <code>soroban-state-ops.toml</code> for automated CLI checks and keeper tracking.
            </p>
          </div>
          <button onClick={copyToml} className="btn btn-primary" style={{ fontSize: "0.8rem" }}>
            {copiedToml ? "✓ Copied TOML!" : "📋 Copy TOML Snippet"}
          </button>
        </div>

        <pre
          className="mono"
          style={{
            background: "var(--bg-elevated)",
            padding: "var(--space-lg)",
            borderRadius: "var(--radius-md)",
            border: "1px solid var(--border-subtle)",
            fontSize: "0.85rem",
            color: "hsl(200, 80%, 75%)",
            overflowX: "auto",
          }}
        >
          {tomlSnippet}
        </pre>
      </div>
    </div>
  );
}
